services:
  server:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "443:443"
    volumes:
      - /ssl/data.hobbylos.online:/usr/src/app/ssl
